import { ContactForm } from "@/components/ContactForm";
import { CoverageDetail } from "@/components/CoverageDetail";
import { HeroSection } from "@/components/HeroSection/HeroSection";
import { respInsuranceItems, respTableData } from "@/data/faqs/resp";
import { Collapse } from "antd";
const RESP = () => {
  return (
    <>
      <HeroSection
        heading={"Registered Education Saving Plan (RESP)"}
        para={`A Registered Education Savings Plan (RESP) is an educational savings
            program supported by the Canadian government. Participants in an
            RESP make contributions that generate tax-free earnings to cover
            higher education expenses. Alongside parental contributions, the
            government also provides a specific contribution to these plans for
            children below the age of 18.`}
        img={"/images/sub/RESP.jpg"}
        color={"#5393becc"}
        position="top"
      />

      <div className="relative top-[-165px]">
        <ContactForm />
      </div>
      <div className="container mx-auto relative top-[-105px] flex flex-col gap-5">
        <div className="space-y-1">
          <h1 className="font-bold text-lg">RESP Insurance</h1>
          <table className="pt-5 w-full text-center overflow-x-auto">
            <thead>
              <tr>
                <th className="border border-black py-7">Year</th>
                <th className="border border-black py-7">
                  Annual Contribution
                </th>
                <th className="border border-black py-7">Government Grants</th>
                <th className="border border-black py-7">
                  Total Contributions
                </th>
                <th className="border border-black py-7">
                  Estimated Future Value
                </th>
              </tr>
            </thead>
            <tbody>
              {respTableData.map((item, i) => (
                <tr key={i++}>
                  <td className="border border-black py-7">Year {item.year}</td>
                  <td className="border border-black py-7">${item.annual}</td>
                  <td className="border border-black py-7">${item.grants}</td>
                  <td className="border border-black py-7">
                    ${item.total_contribution}
                  </td>
                  <td className="border border-black py-7">
                    ${item.future_value}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="pt-6">
            <b> Note: </b>In this table, a $500 government grant is added every
            year, and the annual contribution is $2,500. The total contributions
            column represents the sum of the annual contributions and government
            grants. The RESP's estimated future value is based on a 5% annual
            compounded rate of return.
          </p>
          <p>
            Government grants are calculated based on a 20% Canada Education
            Savings Grant (CESG) for the first $2,500 contributed annually, and
            a 10% grant for contributions above $2,500 up to a maximum CESG of
            $500 per year. The RESP's estimated future value is based on a 5%
            annual compounded rate of return. Actual returns and government
            grants may vary, and contribution limits and rules may change over
            time. Consult with a financial advisor for precise calculations
            tailored to your specific situation.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="font-bold text-lg">Points to Remember</h2>
          <ul className="list-disc ml-6">
            <li className="text-md">
              <b className="underline">Tax-Deferred Growth:</b> Your funds experience tax-deferred growth
              while residing within the RESP. You have the capacity to
              contribute up to $50,000 for each beneficiary. The earnings
              generated by your investment within the RESP remain untaxed until
              the point of withdrawal.
            </li>
            <li className="text-md">
             <b className="underline"> RESP Government Grants:</b> Both federal and select provincial
              governments provide grant and incentive programs designed to boost
              your beneficiary's RESP savings. These grants have no impact on
              your RESP contribution room. For instance, through the Canada
              Education Savings Grant (CESG), the government matches 20% of your
              contributions, up to $2,500 annually. This match extends up to a
              maximum lifetime grant amount of $7,200 per beneficiary.
            </li>
            <li className="text-md">
              <b className="underline">Flexibility:</b> Within the lifetime contribution threshold of $50,000
              for each beneficiary, you retain the freedom to determine when and
              how much you want to contribute. Additionally, you possess the
              autonomy to choose your preferred investment approach.
            </li>
            <li className="text-md">
              <b className="underline">Diverse Investment Options:</b> Funds allocated to your RESP can be
              directed into an array of investment products, encompassing mutual
              funds, ETFs, GICs, stocks, and bonds. The investment options at
              your disposal hinge on the type of RESP plan you select.
            </li>
         
          </ul>
         
        </div>
      </div>
      <div
        id="resp"
        className="p-4"
        style={{ minHeight: "100vh", background: "#5393becc" }}
      >
        <h1 className="text-white font-bold text-2xl">RESP Insurance FAQs</h1>
        <Collapse
          ghost
          items={respInsuranceItems}
          // defaultActiveKey={['1']}
        />
      </div>
    </>
  );
};

export default RESP;
